execute_process(COMMAND "${BENCH}" -m "${MODEL}" -b cpu -p 8 -n 8 -r 2 --warmup 1 --json
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors)
if(NOT status EQUAL 0)
    message(FATAL_ERROR "Benchmark failed: ${errors}")
endif()
string(JSON schema GET "${output}" schema_version)
string(JSON count LENGTH "${output}" results)
string(JSON pp GET "${output}" results 0 test)
string(JSON tg GET "${output}" results 1 test)
string(JSON speed GET "${output}" results 0 tokens_per_second)
if(NOT schema EQUAL 1 OR NOT count EQUAL 2 OR NOT pp STREQUAL "pp8" OR NOT tg STREQUAL "tg8" OR NOT speed GREATER 0)
    message(FATAL_ERROR "Invalid benchmark JSON: ${output}")
endif()
foreach(argument IN ITEMS -1 0 nope 1001)
    execute_process(COMMAND "${BENCH}" -m "${MODEL}" -r "${argument}" RESULT_VARIABLE status OUTPUT_QUIET ERROR_QUIET)
    if(status EQUAL 0)
        message(FATAL_ERROR "Accepted invalid repetition count: ${argument}")
    endif()
endforeach()
execute_process(COMMAND "${BENCH}" -m "${MODEL}" -b invalid RESULT_VARIABLE status OUTPUT_QUIET ERROR_QUIET)
if(status EQUAL 0)
    message(FATAL_ERROR "Accepted invalid backend")
endif()
