# Exercise the shipped executable, including dataset parsing and exact resume.
# Unique output paths permit repeated CTest runs without relaxing the trainer's
# exclusive-output rule or deleting any pre-existing user file.
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef suffix)
set(root "${FIXTURES}/train-cli-${suffix}")
file(MAKE_DIRECTORY "${root}")
file(WRITE "${root}/corpus.txt" "abcabcabcabcabcabcabcabcabcabc")
file(WRITE "${root}/sft.tsv" "a\tbcabc\na\tbcabc\n")
file(WRITE "${root}/dpo.tsv" "a\tbcabc\tccccc\n")
set(dimensions --dimension 16 --ff 32 --layers 1 --heads 2 --kv-heads 1 --context 16)
function(run)
    execute_process(COMMAND "${TRAINER}" ${ARGN} RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "Trainer failed: ${ARGN}\n${output}\n${error}")
    endif()
    message(STATUS "${output}")
endfunction()
run(--data "${root}/corpus.txt" --output "${root}/first.gguf" --checkpoint "${root}/first.ckpt" --steps 30 --lr 0.015 ${dimensions})
run(--data "${root}/corpus.txt" --output "${root}/resumed.gguf" --checkpoint "${root}/resumed.ckpt" --resume "${root}/first.ckpt" --steps 10 --lr 0.015 ${dimensions})
run(--data "${root}/corpus.txt" --output "${root}/continuous.gguf" --checkpoint "${root}/continuous.ckpt" --steps 40 --lr 0.015 ${dimensions})
foreach(extension IN ITEMS gguf ckpt)
    file(SHA256 "${root}/resumed.${extension}" resumed)
    file(SHA256 "${root}/continuous.${extension}" continuous)
    if(NOT resumed STREQUAL continuous)
        message(FATAL_ERROR "Resume differs from uninterrupted training: ${extension}")
    endif()
endforeach()
run(--mode cpt --base "${root}/first.gguf" --rank 0 --data "${root}/corpus.txt" --output "${root}/cpt.gguf" --context 16 --steps 4)
run(--mode sft --base "${root}/first.gguf" --rank 4 --data "${root}/sft.tsv" --output "${root}/sft.gguf" --context 16 --steps 4)
run(--mode dpo --base "${root}/first.gguf" --rank 4 --data "${root}/dpo.tsv" --output "${root}/dpo.gguf" --checkpoint "${root}/dpo.ckpt" --context 16 --steps 4)
run(--mode dpo --base "${root}/first.gguf" --rank 4 --data "${root}/dpo.tsv" --output "${root}/dpo-resumed.gguf" --resume "${root}/dpo.ckpt" --context 16 --steps 2)
run(--mode dpo --base "${root}/first.gguf" --rank 4 --data "${root}/dpo.tsv" --output "${root}/dpo-continuous.gguf" --context 16 --steps 6)
file(SHA256 "${root}/dpo-resumed.gguf" resumed)
file(SHA256 "${root}/dpo-continuous.gguf" continuous)
if(NOT resumed STREQUAL continuous)
    message(FATAL_ERROR "DPO resume changed the reference policy or optimizer state")
endif()
# Bad structured records, invalid integers and existing destinations must fail.
file(WRITE "${root}/bad.tsv" "missing separator\n")
execute_process(COMMAND "${TRAINER}" --mode sft --base "${root}/first.gguf" --data "${root}/bad.tsv" --output "${root}/bad.gguf" RESULT_VARIABLE status OUTPUT_QUIET ERROR_QUIET)
if(status EQUAL 0 OR EXISTS "${root}/bad.gguf")
    message(FATAL_ERROR "Malformed dataset was accepted")
endif()
execute_process(COMMAND "${TRAINER}" --steps -1 RESULT_VARIABLE status OUTPUT_QUIET ERROR_QUIET)
if(status EQUAL 0)
    message(FATAL_ERROR "Negative step count was accepted")
endif()
file(SHA256 "${root}/first.gguf" before)
execute_process(COMMAND "${TRAINER}" --data "${root}/corpus.txt" --output "${root}/first.gguf" --steps 1 ${dimensions} RESULT_VARIABLE status OUTPUT_QUIET ERROR_QUIET)
file(SHA256 "${root}/first.gguf" after)
if(status EQUAL 0 OR NOT before STREQUAL after)
    message(FATAL_ERROR "Existing model was overwritten")
endif()
