# Exercise the shipped executable, including dataset parsing and exact resume.
# Unique output paths permit repeated CTest runs without relaxing the trainer's
# exclusive-output rule or deleting any pre-existing user file.
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef suffix)
set(root "${FIXTURES}/train-cli-${suffix}")
file(MAKE_DIRECTORY "${root}")
file(WRITE "${root}/corpus.txt" "abcabcabcabcabcabcabcabcabcabc")
file(WRITE "${root}/sft.tsv" "a\tbcabc\na\tbcabc\n")
file(WRITE "${root}/dpo.tsv" "a\tbcabc\tccccc\n")
set(dimensions --dimension 16 --ff 32 --layers 1 --heads 2 --kv-heads 1 --context 16)
function(run)
    execute_process(COMMAND "${TRAINER}" ${ARGN} RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "Trainer failed: ${ARGN}\n${output}\n${error}")
    endif()
    message(STATUS "${output}")
endfunction()
run(--data "${root}/corpus.txt" --output "${root}/first.gguf" --checkpoint "${root}/first.ckpt" --metrics "${root}/metrics.csv" --steps 30 --lr 0.015 ${dimensions})
file(STRINGS "${root}/metrics.csv" metric_rows)
list(LENGTH metric_rows metric_count)
if(NOT metric_count EQUAL 31)
    message(FATAL_ERROR "Expected a metrics header and one row per update")
endif()
run(--data "${root}/corpus.txt" --output "${root}/resumed.gguf" --checkpoint "${root}/resumed.ckpt" --resume "${root}/first.ckpt" --steps 10 --lr 0.015 ${dimensions})
run(--data "${root}/corpus.txt" --output "${root}/continuous.gguf" --checkpoint "${root}/continuous.ckpt" --steps 40 --lr 0.015 ${dimensions})
foreach(extension IN ITEMS gguf ckpt)
    file(SHA256 "${root}/resumed.${extension}" resumed)
    file(SHA256 "${root}/continuous.${extension}" continuous)
    if(NOT resumed STREQUAL continuous)
        message(FATAL_ERROR "Resume differs from uninterrupted training: ${extension}")
    endif()
endforeach()
run(--mode cpt --base "${root}/first.gguf" --rank 0 --data "${root}/corpus.txt" --output "${root}/cpt.gguf" --context 16 --steps 4)
run(--mode sft --base "${root}/first.gguf" --rank 4 --data "${root}/sft.tsv" --output "${root}/sft.gguf" --context 16 --steps 4)
run(--mode dpo --base "${root}/first.gguf" --rank 4 --data "${root}/dpo.tsv" --output "${root}/dpo.gguf" --checkpoint "${root}/dpo.ckpt" --context 16 --steps 4)
run(--mode dpo --base "${root}/first.gguf" --rank 4 --data "${root}/dpo.tsv" --output "${root}/dpo-resumed.gguf" --resume "${root}/dpo.ckpt" --context 16 --steps 2)
run(--mode dpo --base "${root}/first.gguf" --rank 4 --data "${root}/dpo.tsv" --output "${root}/dpo-continuous.gguf" --context 16 --steps 6)
file(SHA256 "${root}/dpo-resumed.gguf" resumed)
file(SHA256 "${root}/dpo-continuous.gguf" continuous)
if(NOT resumed STREQUAL continuous)
    message(FATAL_ERROR "DPO resume changed the reference policy or optimizer state")
endif()
# Same-shaped models can have different semantics. Reject changed context,
# dataset, DPO beta and frozen base before writing an output model.
function(reject_resume reason)
    execute_process(COMMAND "${TRAINER}" ${ARGN} --output "${root}/rejected-${reason}.gguf"
        RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(status EQUAL 0 OR EXISTS "${root}/rejected-${reason}.gguf" OR NOT error MATCHES "mismatches")
        message(FATAL_ERROR "Invalid resume ${reason} was not rejected: ${output} ${error}")
    endif()
endfunction()
file(WRITE "${root}/changed.txt" "cbacbacbacbacbacbacbacbacbacba")
reject_resume(data --data "${root}/changed.txt" --resume "${root}/first.ckpt" --steps 1 ${dimensions})
reject_resume(context --data "${root}/corpus.txt" --resume "${root}/first.ckpt" --steps 1 ${dimensions} --context 8)
reject_resume(heads --data "${root}/corpus.txt" --resume "${root}/first.ckpt" --steps 1 ${dimensions} --heads 4 --kv-heads 2)
reject_resume(beta --mode dpo --base "${root}/first.gguf" --rank 4 --data "${root}/dpo.tsv"
    --resume "${root}/dpo.ckpt" --context 16 --steps 1 --beta 0.2)
reject_resume(base --mode dpo --base "${root}/continuous.gguf" --rank 4 --data "${root}/dpo.tsv"
    --resume "${root}/dpo.ckpt" --context 16 --steps 1)
# Accumulation resumes at an update boundary, including groups crossing the
# corpus/record-list end. Use unequal completion lengths and three records so
# a two-record group does not always restart at record zero.
file(WRITE "${root}/uneven-sft.tsv" "a\tbc\nabc\tabcabc\nc\tacba\n")
file(WRITE "${root}/uneven-dpo.tsv" "a\tbc\tc\nabc\tabcabc\tcabc\nc\tacba\tabc\n")
foreach(mode IN ITEMS pretrain cpt sft dpo)
    set(args --mode ${mode} --data "${root}/corpus.txt" --accumulate 3 ${dimensions})
    if(NOT mode STREQUAL pretrain)
        list(APPEND args --base "${root}/first.gguf" --rank 4)
    endif()
    if(mode STREQUAL sft OR mode STREQUAL dpo)
        list(APPEND args --data "${root}/uneven-${mode}.tsv" --accumulate 2)
    endif()
    run(${args} --steps 2 --output "${root}/${mode}-acc-first.gguf" --checkpoint "${root}/${mode}-acc-first.ckpt")
    run(${args} --steps 3 --resume "${root}/${mode}-acc-first.ckpt"
        --output "${root}/${mode}-acc-resume.gguf" --checkpoint "${root}/${mode}-acc-resume.ckpt")
    run(${args} --steps 5 --output "${root}/${mode}-acc-full.gguf" --checkpoint "${root}/${mode}-acc-full.ckpt"
        --metrics "${root}/${mode}-acc.csv")
    foreach(extension IN ITEMS gguf ckpt)
        file(SHA256 "${root}/${mode}-acc-resume.${extension}" resumed)
        file(SHA256 "${root}/${mode}-acc-full.${extension}" continuous)
        if(NOT resumed STREQUAL continuous)
            message(FATAL_ERROR "Accumulated ${mode} ${extension} changed on resume")
        endif()
    endforeach()
    reject_resume(${mode}-accumulation ${args} --accumulate 1 --steps 1 --resume "${root}/${mode}-acc-first.ckpt")
endforeach()
reject_resume(single-to-accumulated --data "${root}/corpus.txt" --resume "${root}/first.ckpt" --steps 1 ${dimensions} --accumulate 2)
# Bad structured records, invalid integers and existing destinations must fail.
file(WRITE "${root}/bad.tsv" "missing separator\n")
execute_process(COMMAND "${TRAINER}" --mode sft --base "${root}/first.gguf" --data "${root}/bad.tsv" --output "${root}/bad.gguf" RESULT_VARIABLE status OUTPUT_QUIET ERROR_QUIET)
if(status EQUAL 0 OR EXISTS "${root}/bad.gguf")
    message(FATAL_ERROR "Malformed dataset was accepted")
endif()
execute_process(COMMAND "${TRAINER}" --steps -1 RESULT_VARIABLE status OUTPUT_QUIET ERROR_QUIET)
if(status EQUAL 0)
    message(FATAL_ERROR "Negative step count was accepted")
endif()
foreach(value IN ITEMS 0 1025 -1 1.5 18446744073709551616)
    execute_process(COMMAND "${TRAINER}" --data "${root}/corpus.txt" --output "${root}/invalid-acc.gguf"
        --accumulate "${value}" RESULT_VARIABLE status OUTPUT_QUIET ERROR_QUIET)
    if(status EQUAL 0 OR EXISTS "${root}/invalid-acc.gguf")
        message(FATAL_ERROR "Invalid accumulation value was accepted: ${value}")
    endif()
endforeach()
foreach(value IN ITEMS 65 -1 1.5 18446744073709551616)
    execute_process(COMMAND "${TRAINER}" --data "${root}/corpus.txt" --output "${root}/invalid-threads.gguf"
        --threads "${value}" RESULT_VARIABLE status OUTPUT_QUIET ERROR_QUIET)
    if(status EQUAL 0 OR EXISTS "${root}/invalid-threads.gguf")
        message(FATAL_ERROR "Invalid CPU thread count was accepted: ${value}")
    endif()
endforeach()
# Changing worker count must not change saved optimizer/data semantics. These
# shapes exceed the dispatch threshold, including uneven dense output widths.
string(REPEAT "abc" 180 parallel_corpus)
file(WRITE "${root}/parallel.txt" "${parallel_corpus}")
set(parallel_args --data "${root}/parallel.txt" --dimension 64 --ff 176 --layers 1
    --heads 4 --kv-heads 2 --context 128 --accumulate 3)
run(${parallel_args} --threads 1 --steps 2 --output "${root}/parallel-first.gguf" --checkpoint "${root}/parallel-first.ckpt")
run(${parallel_args} --threads 3 --steps 3 --resume "${root}/parallel-first.ckpt"
    --output "${root}/parallel-resumed.gguf" --checkpoint "${root}/parallel-resumed.ckpt")
run(${parallel_args} --threads 6 --steps 5 --output "${root}/parallel-full.gguf" --checkpoint "${root}/parallel-full.ckpt")
foreach(extension IN ITEMS gguf ckpt)
    file(SHA256 "${root}/parallel-resumed.${extension}" resumed)
    file(SHA256 "${root}/parallel-full.${extension}" continuous)
    if(NOT resumed STREQUAL continuous)
        message(FATAL_ERROR "Changing worker count changed resumed ${extension}")
    endif()
endforeach()
file(SHA256 "${root}/first.gguf" before)
execute_process(COMMAND "${TRAINER}" --data "${root}/corpus.txt" --output "${root}/first.gguf" --steps 1 ${dimensions} RESULT_VARIABLE status OUTPUT_QUIET ERROR_QUIET)
file(SHA256 "${root}/first.gguf" after)
if(status EQUAL 0 OR NOT before STREQUAL after)
    message(FATAL_ERROR "Existing model was overwritten")
endif()
