// Render-only workspace components. All model paths and remote/imported text are
// escaped; controls carry only validated numeric registry IDs and fixed enums.
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const name=m=>m?.path?.split(/[\\/]/).pop()||'No model selected';
const chip='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4" aria-hidden="true"><rect x="6" y="6" width="12" height="12" rx="2"/><path d="M9 2v4m6-4v4M9 18v4m6-4v4M2 9h4m-4 6h4m12-6h4m-4 6h4"/></svg>';
export function workspaceMarkup(s){
  const selected=s.models.find(m=>m.id===s.selected),runtime=s.runtime?.models?.find(m=>m.model_id===s.selected);
  const available=s.runtime?.compiled;
  const rows=s.models.map(m=>{
    const active=s.runtime?.models?.find(r=>r.model_id===m.id);
    return `<article class="model-row ${m.id===s.selected?'selected':''}"><span class="model-emblem">${chip}</span><div class="model-info"><button data-model="${m.id}" ${m.generation_supported?'':'disabled'}>${esc(name(m))}</button><p>${esc(m.architecture||m.format)} <span>·</span> ${(m.file_size/1024**3).toFixed(2)} GB <span>·</span> ${m.generation_supported?'Text generation':m.draft_supported?'MTP assistant':m.inference_supported?'Tensor execution':'Inspection only'}</p></div><span class="provider-tag ${active?.compute==='cuda'?'cuda':''}">${esc(active?.compute||'—')}</span><button class="icon-button" data-unload="${m.id}" aria-label="Unload ${esc(name(m))}" ${s.busy||s.actionBusy?'disabled':''}>×</button></article>`;
  }).join('');
  return `<div class="workspace-view"><section class="workspace-intro"><div><label class="eyebrow">YOUR LOCAL WORKSPACE</label><h1>Everything starts here<span>.</span></h1><p>Load a model. Find a thought. Make it your own.</p></div><button class="load-model primary">+ Load model</button></section>
  <div class="metric-strip"><div><label>ENGINE STATUS</label><b><i class="status-dot ${s.health?'online':''}"></i>${s.health?'Connected':'Offline'}</b></div><div><label>LOADED MODELS</label><b>${String(s.models.length).padStart(2,'0')}<small> / 32</small></b></div><div><label>SELECTED COMPUTE</label><b class="warm">${esc(runtime?.compute?.toUpperCase()||'—')}<small>${selected?'active model':'load a model'}</small></b></div><div><label>CONVERSATIONS</label><b>${String(s.chats.length).padStart(2,'0')}</b></div></div>
  ${!s.health?'<div class="offline-note"><span>The local engine is offline. Open the desktop app or connect a development backend.</span><button data-refresh>Reconnect ↻</button></div>':''}
  <div class="workspace-grid"><section class="panel model-library"><header><div><label>01 / MODEL LIBRARY</label><h2>On your machine</h2></div><button data-refresh>Refresh ↻</button></header><div class="model-stack">${rows||`<div class="empty-library"><span>${chip}</span><h3>A home for your models</h3><p>Open a GGUF for local inference, or inspect<br>an ONNX or SafeTensors file.</p><button class="load-model secondary">Browse models ↗</button></div>`}</div><div class="panel-foot"><span>FILES STAY ON YOUR DEVICE</span><span>GGUF / ONNX / SAFETENSORS</span></div></section>
  <section class="panel runtime-panel"><header><div><label>02 / ACCELERATION</label><h2>A little more power</h2></div><span class="chip-outline">${chip}</span></header><p class="muted">Choose how your selected model runs.</p><div class="runtime-target">${esc(name(selected))}</div><div class="compute-switch" role="group" aria-label="Compute provider">${['cpu','cuda','vulkan'].map(p=>`<button data-compute="${p}" data-id="${s.selected||0}" aria-pressed="${runtime?.compute===p}" class="${runtime?.compute===p?'active':''}" ${!runtime?.selectable||!available?.[p]||s.actionBusy||s.busy?'disabled':''}>${p.toUpperCase()}</button>`).join('')}</div><dl class="runtime-details"><div><dt>CUDA build</dt><dd>${available?available.cuda?'Included':'Not included':'—'}</dd></div><div><dt>Vulkan build</dt><dd>${available?available.vulkan?'Included':'Not included':'—'}</dd></div><div><dt>Training</dt><dd>CPU autograd</dd></div></dl><p class="fine-print">GPU selection is verified on device. Unsupported operations keep their CPU path.</p><div class="runtime-decoration" aria-hidden="true"><i></i><i></i><i></i><b>COMPUTE / LOCAL</b></div></section>
  <section class="panel recent-panel"><header><div><label>03 / PICK UP A THREAD</label><h2>Recent conversations</h2></div><button data-new-chat>New chat +</button></header>${s.chats.slice(0,4).map(c=>`<button class="recent-row" data-chat="${c.id}"><span class="recent-icon">◌</span><span><b>${esc(c.title)}</b><small>${new Date(c.created).toLocaleDateString(undefined,{month:'short',day:'numeric'})} · ${c.messages.length} messages</small></span><em>↗</em></button>`).join('')||'<p class="quiet-empty">Your next conversation starts with a question.</p>'}</section>
  <section class="tool-cards"><button data-view="playground" class="tool-card blue"><label>EXPLORE / 01</label><h3>Room to experiment</h3><p>Take a prompt apart. Tune every detail.</p><b>Open playground ↗</b></button><button data-view="training" class="tool-card orange"><label>BUILD / 02</label><h3>Teach it something</h3><p>From the first weight to the next checkpoint.</p><b>Open training ↗</b></button></section></div></div>`;
}
export function apiMarkup(s){return `<div class="workspace-view api-page"><section class="workspace-intro"><div><label class="eyebrow">INTEGRATIONS / LOCAL REST</label><h1>Your models. Your tools.</h1><p>Connect an SDK or application to the same local engine.</p></div><span class="provider-tag">TEXT · NON-STREAMING</span></section><div class="api-cards">${[['Native REST','/api/v1','Model lifecycle, runtime selection, tokenization and draft controls.'],['OpenAI compatible','/openai/v1','Chat Completions, Completions and model listing.'],['Anthropic compatible','/anthropic','Messages, model listing and token counting.']].map(([label,path,description])=>`<section class="panel"><label>LOCAL ENDPOINT</label><h2>${label}</h2><p class="muted">${description}</p><code>${esc(s.baseUrl+path)}</code><button data-copy-url="${path}">Copy base URL ↗</button></section>`).join('')}</div><section class="panel api-example"><header><div><label>NATIVE / PER-MODEL CONTROL</label><h2>Put the engine to work.</h2></div></header><pre>${esc(`POST ${s.baseUrl}/api/v1/model/compute\nAuthorization: Bearer <local process token>\nContent-Type: application/json\n\n{"model_id": ${s.selected||1}, "compute": "cuda"}\n\nGET  /api/v1/runtime\nPOST /api/v1/model/info   {"model_id": ${s.selected||1}}\nPOST /api/v1/tokenize     {"model_id": ${s.selected||1}, "text": "Hello"}`)}</pre><p class="fine-print">Use the local process token, not a vendor key. Streaming, tools and media messages are not supported by the compatibility adapters. Native generation additionally accepts top_k, seed, draft_model_id and speculative_tokens.</p><button class="secondary" data-copy-token>Copy local API token</button></section></div>`;}
