"""Generate committed C/CSS/JS adapters. Python is a maintainer-only dependency."""
import argparse
import json
from pathlib import Path
import re

root = Path(__file__).resolve().parent.parent
spec = json.loads((root / 'themes/palettes.json').read_text(encoding='utf-8'))
assert spec['schema'] == 1
roles = spec['roles']
assert len(roles) == len(set(roles)) == 18
themes = spec['themes']
vendor = json.loads((root / 'themes/vendor/catppuccin.json').read_text(encoding='utf-8'))
for flavor in ('latte', 'frappe', 'macchiato', 'mocha'):
    palette = vendor[flavor]
    mapping = {**spec['catppuccin'], **spec.get('catppuccin_overrides', {}).get(flavor, {})}
    themes.append(dict(id='catppuccin-' + flavor, name='Catppuccin ' + palette['name'], dark=palette['dark'],
                       colors=[palette['colors'][mapping[r]]['hex'] for r in roles]))
assert len({t['id'] for t in themes}) == len(themes)
for theme in themes:
    assert re.fullmatch('[a-z][a-z0-9-]+', theme['id'])
    assert len(theme['colors']) == len(roles)
    assert all(re.fullmatch('#[0-9a-fA-F]{6}', c) for c in theme['colors'])
    theme['roles'] = dict(zip(roles, theme.pop('colors')))

header = '/* Generated by scripts/generate-themes.py; Catppuccin: themes/vendor/CATPPUCCIN-LICENSE. */\n'
c = header + 'static const fyodor_theme builtin_themes[] = {\n'
for t in themes:
    c += '    {' + json.dumps(t['id']) + ', ' + json.dumps(t['name'], ensure_ascii=True) + ', {'
    c += ','.join('0x' + color[1:] + 'u' for color in t['roles'].values()) + '}},\n'
c += '};\n'
# Keep C source ASCII and use UTF-8 octal escapes for display labels.
for char in set(c):
    if ord(char) > 127:
        c = c.replace(char, ''.join('\\%03o' % b for b in char.encode('utf-8')))
js = header + 'window.fyodorThemes = Object.freeze(' + json.dumps(themes, ensure_ascii=True, separators=(',', ':')) + '.map(t => Object.freeze({...t, roles: Object.freeze(t.roles)})));\n'
aliases = dict(bg='background', raised='surface_raised', input='background', line='border',
               **{'line-strong':'focus', 'muted':'text_muted', 'blue':'info', 'accent-soft':'selection',
                  'on-accent':'accent_text', 'orange':'warning', 'danger':'error'})
css = header
for t in themes:
    css += (':root, ' if t['id'] == 'fyodor' else '') + f':root[data-theme="{t["id"]}"] {{\n'
    css += '  color-scheme: ' + ('dark' if t['dark'] else 'light') + ';\n'
    css += ''.join(f'  --{role.replace("_", "-")}: {color};\n' for role,color in t['roles'].items())
    css += ''.join(f'  --{alias}: var(--{role.replace("_", "-")});\n' for alias,role in aliases.items())
    css += '  --danger-soft: color-mix(in srgb, var(--error) 12%, var(--surface));\n'
    css += '  --shadow: 0 14px 46px color-mix(in srgb, var(--background) 60%, transparent);\n'
    css += '  --scrim: color-mix(in srgb, var(--text) 45%, transparent);\n}\n'
license_text = (root / 'themes/vendor/CATPPUCCIN-LICENSE').read_text(encoding='utf-8')
c += 'static const char theme_license[] = ' + json.dumps('Catppuccin palette 1.8.0\nhttps://github.com/catppuccin/palette\n\n' + license_text) + ';\n'
outputs = {'backend/core/fyodor_themes.inc': c, 'frontend/public/themes.js': js, 'frontend/src/themes.css': css,
           'frontend/public/theme-licenses.txt': 'Catppuccin palette 1.8.0\nhttps://github.com/catppuccin/palette\n\n' + license_text}
check = argparse.ArgumentParser()
check.add_argument('--check', action='store_true')
args = check.parse_args()
for name, content in outputs.items():
    path = root / name
    if args.check:
        assert path.read_text(encoding='utf-8') == content, f'{name} needs regeneration'
    else:
        path.write_text(content, encoding='utf-8', newline='\n')
